### ISSUE TITLE
resnet的卷积核大小

### ISSUE THREAD

**Issue by hefangnan** [YOLOonMe/EMA-attention-module#4]
您好，看到您提供的resnet50上训练的权重文件，在一开头使用的是3×3大小的卷积核，而并非官方提供的7乘7大小的卷积核，而且3×3的卷积核只有一层，请问这样不会导致感受野不同而对最终的性能产生影响吗？
![Snipaste_2023-09-18_21-57-46](https://github.com/YOLOonMe/EMA-attention-module/assets/52640516/4882955f-4ff3-4779-82ee-9fae77ae23d7)

**Comment by YOLOonMe** [comment]
@hefangnan 1. 3x3卷积核是对比的基准方案里面的，我直接采用了只是为了方便对比[NAM](https://github.com/Christian-lyc/NAM)； 2. 个人认为：7x7的感受野更大可以捕获更多的邻近上下文，但是实验中采用的CIFAR数据尺寸太小，3x3影响不大。

**Comment by hefangnan** [comment]
谢谢您的及时回复！因为我的实验对象都是高分辨率的图像，所以要用到7×7大小的卷积核。如果我直接将EMA添加到res50中，再使用原本的res50的预训练权重进行训练，您觉得对实验结果有影响吗？

**Comment by YOLOonMe** [comment]
这个也许行吧，只在imagenet1k这中224x224做过实验，其他的数据集不好说效果会怎么样

**Comment by hefangnan** [comment]
好的 十分感谢！
